### ISSUE TITLE
Missing toolbar icon in recent versions of Discourse

### ISSUE THREAD

**Issue by samny** [ThomDietrich/discourse-plugin-code-fences-buttons#4]
The toolbar icon "file-code-o" is not available in Discourse anymore since they [switched to SVG icons ](https://meta.discourse.org/t/introducing-font-awesome-5-and-svg-icons/101643) in version 2.2.0

Bundled icons can be found [here](https://github.com/discourse/discourse/blob/6d2708c3fb1e59db762dd85aa33b4e21061b7017/lib/svg_sprite/svg_sprite.rb)

**Comment by ThomDietrich** [comment]
Hey @samny thanks for the report! This is something we need to fix quickly. You already seem to know what needs to be changed. Would you like to submit a PR or give some further suggestions on how to resolve the issue?

**Comment by daniel-cabral** [comment]
Same here!

**Comment by ThomDietrich** [comment]
Happy to merge a PR.
@daniel-cabral are you able to create a tested solution?

**Comment by daniel-cabral** [comment]
@ThomDietrich , atm I'm unable to lead the hotfix but I can help you with it. I'm new to Discourse world, made the forum https://fluiggers.com.br/ for our dev community here. You can see the issue in any topic reply, I left it activated.

**Comment by ThomDietrich** [comment]
Maybe you could ask any of your dev friends to contribute a PR? :) I have currently no Discourse community to test with.

**Comment by daniel-cabral** [comment]
Hey @ThomDietrich ! A good soul friend of ours did the PR - https://github.com/ThomDietrich/discourse-plugin-code-fences-buttons/pull/5

**Comment by AGulev** [comment]
according to documentation icons should be registered https://meta.discourse.org/t/introducing-font-awesome-5-and-svg-icons/101643
the icons still invisible

**Comment by AGulev** [comment]
Hi @ThomDietrich 
Icons are still missed.
I prepared PR: https://github.com/ThomDietrich/discourse-plugin-code-fences-buttons/pull/6

I tested it locally to be 100% sure it works:

![](https://user-images.githubusercontent.com/2209596/118333927-e3bd4880-b50c-11eb-9e9c-4dee5588f805.png)

**Comment by AGulev** [comment]
and all the icons 
![image](https://user-images.githubusercontent.com/2209596/118334753-80341a80-b50e-11eb-8731-8cef18a0f6d0.png)

**Comment by ThomDietrich** [comment]
Thanks @AGulev ! 🚀

**Comment by daniel-cabral** [comment]
Niiiiiiiiiiice! Thanks @AGulev !

**Comment by AGulev** [comment]
@ThomDietrich @daniel-cabral no problem )
